# -*- coding: utf-8 -*-
"""NDVI_phenology.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12eSmRTSV79sungyseOlo_cGrC2mGL0ND
"""

import ee
import geemap
!pip install xee
import xee
import xarray as xr

ee.Authenticate()
ee.Initialize(
    project = 'ee-lavibas23',
    opt_url = 'https://earthengine-highvolume.googleapis.com'
)

map = geemap.Map(basemap = 'SATELLITE')
map

roi = map.draw_last_feature.geometry()

roi

collection = (
    ee.ImageCollection("NOAA/CDR/AVHRR/NDVI/V5")
    .filterDate('2016','2017')
    .select('NDVI')
    .map(lambda img: img.multiply(0.0001).copyProperties(img, img.propertyNames()))
)

collection

ds  = xr.open_dataset(
    collection,
    engine = 'ee',
    crs = 'EPSG:4326',
    scale = 0.01,
    geometry = roi
)

ds

df = ds.to_dataframe().reset_index()[['time','NDVI']].set_index('time').interpolate(method = 'linear')

from scipy.signal import savgol_filter

df['NDVI_smoothed'] = savgol_filter(
    df['NDVI'],
    window_length = 30,
    polyorder = 2
)

df['NDVI_smoothed'].plot()

df.plot()

thresh = 0.35
sos = df['NDVI_smoothed'][df['NDVI_smoothed'] > thresh].index[0].date()
print(f'start of growing season (sos): {sos}')
eos = df['NDVI_smoothed'][df['NDVI_smoothed'] > thresh].index[-1].date()
print(f'end of growing season (eos): {eos}')
los = (eos - sos).days + 1
print(f'length of growing season (los): {los}')